<?php
$this->title = "Delete user";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete
  '<?php echo $this->escape($this->user['username']); ?>' with
  '<?php echo $this->escape($this->user['role']); ?>' privileges ?
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>