<?php
$this->title = "User Management";
$this->headTitle($this->title);
?>
<h3>List of registered users</h3>
<br/>
<p><a href="<?php echo $this->url(array('controller'=>'user',
        'action'=>'add'));?>">Add new user</a></p>
<table>
<tr>
    <th>User Name</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Mobile</th>
    <th>Active</th>
    <th>Admin</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>    
    <td><?php echo $this->escape($user->username);?></td>
    <td><?php echo $this->escape($user->fname);?></td>
    <td><?php echo $this->escape($user->lname);?></td>
    <td><?php echo $this->escape($user->email);?></td>
    <td><?php echo $this->escape($user->mobile);?></td>
    <td><?php echo $this->escape($user->isactive);?></td>
    <td><?php echo $this->escape($user->isadmin);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'edit', 'id'=>$user->id));?>">Change</a>
        <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>