<?php
$this->title = "View Reports";
$this->headTitle($this->title);
?>
<div id="notice" class="warning">
   
</div>
<br/>
<h3>Showing entries for DWP No.: <?php if(isset($this->dwpno)) echo $this->escape($this->dwpno); ?></h3>

<br/>
<table>
    <tr>
        <th>DWP No.</th>
        <th>Date</th>
        <th>Category</th>
        <th>Customer</th>
        <th>Customer Info</th>
        <th>Area</th>
        <th>City</th>
        <th>Visiting Time</th>
        <th>Activity</th>
        <th>Result</th>
        <th>Remarks</th>        
    </tr>
    <?php foreach($this->entries as $entry) : ?>
    <tr>
        <td><?php echo $this->escape($entry->dwpno);?></td>
        <td><?php echo $this->escape($entry->date);?></td>
        <td><?php echo $this->escape($entry->cat);?></td>
        <td><?php echo $this->escape($entry->customer);?></td>
        <td><?php echo $this->escape($entry->customerInfo);?></td>
        <td><?php echo $this->escape($entry->area);?></td>
        <td><?php echo $this->escape($entry->city);?></td>
        <td><?php echo $this->escape($entry->visitTime);?></td>
        <td><?php echo $this->escape($entry->activity);?></td>
        <td><?php echo $this->escape($entry->result);?></td>
        <td><?php echo $this->escape($entry->remarks);?></td>        
    </tr>
    <?php endforeach; ?>
</table>