<?php $this->headLink()->prependStylesheet($this->baseUrl()."/css/default/main.css"); ?>
<div id="display-date"><p><b>Date: <?php echo date("d-m-Y"); ?></b></p></div>
<div id="welcome">
    <br/>
    <h3>This is your Dashboard</h3>
    <div id="links-list">
        <p>
            Helpful Links: <br/><br>
            <a href="/admin/user">User Management</a> | <a href="/admin/report">View Reports</a>
        </p>        
    </div>
</div>