<?php $this->headLink()->prependStylesheet($this->baseUrl()."/css/default/main.css"); ?>
<div id="welcome">
    <br/>
    <h3>This is your Dashboard</h3>
    <br/>
    <div id="links-list">
        <p>Helpful Links:</p>
        <p>            
            <a href="/admin/user">Manage Users</a> | <a href="/admin/report">View Reports</a>
        </p>        
        <p>
            <a href="/admin/customer/index">Manage Customer Categories</a> | <a href="#">View PDFs</a>
        </p>
    </div>
</div>