<?php
$this->title = "New ".$this->entityName;
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/cat-form.css');
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1>Enter new category details</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <?php echo $this->form; ?>
        <br/><div><a href="/admin/cat">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->
