<?php $this->headLink()->prependStylesheet($this->baseUrl()."/css/default/main.css"); ?>
<div id="display-date"><p><b>Date: <?php echo $this->date; ?></b></p></div>
<div id="welcome">
    <h1>Welcome to the <span id="site-name">DCR Home Page</span></h1>

    <h3>Please select your task below.</h3><br/>
    <div id="task-list">
        <br/>        
        <p>           
            <a href="/entry/add">Add New Customer Entry</a> |
            <a href="/entry">View All Entries</a>
        </p>
    </div>
</div>