<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #91BE3F;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="display-date">Date: [Show date]</div><br/>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">DCR Home Page</span></h1>

    <h3>Please select a link below.</h3>

    <div id="more-information">        
        <p>           
            <a href="/entry/add">Add New Customer Entry</a> |
            <a href="/entry">View All Entries</a>
        </p>
    </div>
</div>