<?php
$this->title = "New ".$this->entityName;
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/entry-form.css');
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Add new customer entry</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <img style="display:none;" id="loading-img" src="/images/loading.gif" />
       <?php echo $this->form; ?>
        <br/><div><a href="/entry">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->

<!-- JavaScript -->

<script type="text/javascript" src="/js/jquery/1.8.1.min.js"></script>
<script type="text/javascript" src="/js/ajax/entry-form.js"></script>

<!-- -->