<?php
$this->title = "New ".$this->entityName;
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/entry-form.css');
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Add new customer entry</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <img style="display:none;" id="loading-img" src="/images/loading.gif" />
       <?php echo $this->form; ?>
        <br/><div><a href="/entry">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->

<!-- JavaScript -->

<script type="text/javascript" src="/js/jquery/1.8.1.min.js"></script>
<script>
    $(document).ready(function(){
        //alert("hi");
	$('#area').change(function(){
		var id = $('#area').val();
		$('#loading-img').fadeIn("slow");
		$('#city').css("display", "none");

		$.ajax({
			type:'POST',
			dataType: 'json',
                        url: '/async/loadcity',
			async:false,
                        data: {sel_area: id},
                        cache: false,

			success: function(result){
				$('#loading-img').css("display", "none");
				$('#city').fadeIn("slow");

                                var options = $("#city");
                                options.empty();
                                $.each(result, function() {
                                    options.append($("<option />").val(this.name).text(this.name));
                                });

			}
		});
	});
    });
</script>

<!-- -->