<?php
$this->title = "Delete ".$this->entityName;
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/entry-form.css');
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Warning! Delete <?php echo $this->escape($this->entityName); ?> Permanently ?</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">        
        <p>Are you sure that you want to delete this entry ?
        </p>
        <p style="color:red;">Warning! this action cannot be undone.</p>

        <form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
            <div>
              <input type="hidden" name="id" value="<?php echo $this->entry->id; ?>" />
              <input type="submit" name="del" value="Yes" />
              <input type="submit" name="del" value="No" />
            </div>
        </form>

    </div>
    
</div>
<!-- END Content -->
