<?php
$this->title = "Change User";
$this->headTitle($this->title);
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Edit user's details.</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <?php echo $this->form; ?>
        <br/><div><a href="/admin/user">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->