<?php
$this->title = "Customer Entries";
$this->headTitle($this->title);
?>
<h2>Today's Customer Entries</h2>
<p><a href="<?php echo $this->url(array('controller'=>'entry',
        'action'=>'add'));?>">Add new entry</a></p>
<table style="padding: 2px;" border="2px solid red" >
<tr>
    <th>DWP No.</th>
    <th>Date</th>
    <th>Customer Name</th>
    <th>Customer Info</th>
    <th>Visiting Time</th>
    <th>Area</th>
    <th>City</th>
    <th>Activity</th>
    <th>Result</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->entries as $entry) : ?>
<tr>
    <td><?php echo $this->escape($entry->dwpno);?></td>
    <td><?php echo $this->escape($entry->date);?></td>
    <td><?php echo $this->escape($entry->customer);?></td>
    <td><?php echo $this->escape($entry->customerInfo);?></td>
    <td><?php echo $this->escape($entry->visitTime);?></td>
    <td><?php echo $this->escape($entry->area);?></td>
    <td><?php echo $this->escape($entry->city);?></td>
    <td><?php echo $this->escape($entry->activity);?></td>
    <td><?php echo $this->escape($entry->result);?></td>
    <td>
        <a href="<?php echo $this->url(array('controller'=>'entry',
            'action'=>'edit', 'id'=>$entry->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'user',
            'action'=>'delete', 'id'=>$entry->id));?>">Remove</a>
    </td>

</tr>
<?php endforeach; ?>
</table>