<?php
$this->title = "Update ".$this->entityName;
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/entry-form.css');
?>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Update Entry Result</h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <?php echo $this->form; ?>
        <br/><div><a href="/entry">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->