<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('DCR Admin');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/template/style.css'); ?>
</head>
<body>
    <div id="header-wrapper">
        <div id="header-wrapper-2">
            <div class="center-wrapper">
                <div id="header">
                    <div id="logo">
                        <div class="right">
                            <h3><?php echo date('D M j, Y'); ?></h3>
                        </div>
                        <div class="clearer">&nbsp;</div>
                        <div class="right">
                            <h3><?php echo date('g:i a'); ?></h3>
                        </div>
                        <h1 id="site-title"><a href="/admin">Admin <span>Section</span></a></h1>
                        <h2 id="site-slogan">DCR Management</h2>
                        
                    </div>
                    <div id="help-wrapper">
                        <div id="help">
                            <a href="/admin/report">Reports</a> <span class="text-separator">|</span> <a href="#">Settings</a> <span class="text-separator">|</span> <a href="#">Sitemap</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <!-- End of header -->

    <div id="navigation-wrapper">
        <div id="navigation-wrapper-2">
            <div class="center-wrapper">
                <div id="navigation">
                    <ul class="tabbed">                        
                        <li class="current_page_item"><a href="/admin">Dashboard</a></li>
                        <li><a href="/admin/auth/logout">Logout</a></li>
                    </ul>
                    <div class="clearer">&nbsp;</div>
                </div>

            </div>
        </div>
    </div>
    <!-- End of navigation -->

    <div id="content-wrapper">
        <div class="center-wrapper">
            <div class="content">
                <div id="main">
                    <div id="loggedInAs"><?php echo $this->loggedInAs(); ?></div>
                    <br/>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </div>
    <!-- End of content -->

    <div id="footer-wrapper">
        <div class="center-wrapper">
            <div id="footer">
                <div class="left">
                    <a href="/">Home</a><span class="text-separator">|</span><a href="#">Contact</a><span class="text-separator">|</span><a href="#">Feedback</a><span class="text-separator">|</span><a href="#">Report a bug</a>
                </div>
                <div class="right">
                    <a href="#">Top ^</a>
                </div>
                <div class="clearer">&nbsp;</div>
            </div>
        </div>
    </div>

    <div id="bottom">
        <div class="center-wrapper">
            <div class="left">
                &copy; 2013 DCR - marketing reports <span class="text-separator">|</span> <a href="#">Privacy Policy</a> <span class="text-separator">|</span> <a href="#">Terms of Use</a>
            </div>
            <div class="right">
                <a href="http://templates.arcsin.se/">Website template</a> by <a href="http://arcsin.se/">Arcsin</a>
            </div>
            <div class="clearer">&nbsp;</div>
        </div>
    </div>
    
</body>
</html>


    

    