<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('DCR Admin');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/default/main.css'); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <div id="loggedInAs"><?php echo $this->loggedInAs(); ?></div>
        <div id="topnavi" class="topnavi">
            <ul>
                <li><a href="/admin">Dashboard</a></li>
                <li><a href="#">About</a></li>
            </ul>
        </div>

        <?php echo $this->layout()->content; ?>
    </body>
</html>

