<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('DCR Webapp');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/default/main.css'); ?>

    </head>
    <body>
        <div id="loggedInAs"><?php echo $this->loggedInAs(); ?></div>
        <div id="topnavi" class="topnavi">
            <?php echo $this->navigation()->menu(); ?>
        </div>

        <?php echo $this->layout()->content; ?>
    </body>
</html>

