<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('DCR Admin');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/main.css'); ?>    
    <?php echo $this->headLink(); ?>
</head>
    <body class="myform">
        <!-- Container -->
        <div id="container">
            
            <?php echo $this->layout()->content; ?>
     
            <div id="footer"></div>
        </div>
        <!-- END Container -->
        <script type="text/javascript">
            document.getElementById('id_username').focus()
        </script>
    </body>
</html>

