<?php
$title = "Add ".$this->entity_name;
$this->headTitle($title);
$this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/customer-form.css');
?>

<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name">Add New <?php echo $this->escape($this->entity_name) ?></h1>
    </div>
</div>
<!-- END Header -->

<!-- Content -->
<div id="content" class="colM">
    <div id="content-main">
       <img style="display:none;" id="loading-img" src="/images/loading.gif" />
       <?php echo $this->form; ?>
        <br/><div><a href="/admin">Cancel</a></div>
    </div>
    <br class="clear" />
</div>
<!-- END Content -->

<!-- JavaScript -->
<?php echo $this->inlineScript()->appendFile($this->baseUrl().'/js/jquery/1.8.1.min.js')
            ->appendFile($this->baseUrl().'/js/ajax/form.js')
            ->appendFile($this->baseUrl().'/js/entry-form.js'); ?>
<!-- -->