<?php
$title = "Customer Categories";
$this->headTitle($title);
?>
<h3>Customer Categories</h3>
<br/>
<ul>
    <li>
        <p>
            <a href="/admin/c/doctor/list">Doctors</a>
        </p>
    </li>
    <li>
        <p>
            <a href="/admin/c/pharmacy/list">Pharmacies</a>
        </p>

    </li>
    <li>
        <p>
            <a href="/admin/c/salon/list">Salons
            </a>
        </p>
    </li>
    <li>
        <p>
            <a href="/admin/c/supermarket/list">SuperMarkets</a>
        </p>
    </li>
</ul>